# Generated by Django 3.2.3 on 2021-10-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('date', models.DateField()),
                ('phone', models.CharField(help_text='e.g 254712860997', max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('special_request', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_complete', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'School Tour Request',
                'verbose_name_plural': 'School Tour Requests',
                'ordering': ['timestamp'],
            },
        ),
    ]
