# Generated by Django 3.2.3 on 2021-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_schooltourrequest_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltourrequest',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
