# Generated by Django 3.2.3 on 2021-10-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schooltourrequest_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(default='images/event.jpg', upload_to='images/events/%Y/%m/%d/'),
        ),
    ]
