# Generated by Django 3.2.3 on 2021-10-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211012_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='studentclass',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
