# Generated by Django 3.2.3 on 2021-11-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211013_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_file',
            field=models.FileField(blank=True, null=True, upload_to='files/news/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='news',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
