# Generated by Django 3.2.3 on 2021-12-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211201_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, null=True, upload_to='files/event/%Y/%m/%d'),
        ),
    ]
