# Generated by Django 3.2.3 on 2022-01-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_news_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='images/notice/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('news_file', models.FileField(blank=True, null=True, upload_to='files/news/%Y/%m/%d')),
                ('slug', models.SlugField(blank=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
            },
        ),
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='NoticeCategory',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterModelOptions(
            name='noticecategory',
            options={'verbose_name': 'Notice Category', 'verbose_name_plural': 'Notice Categories'},
        ),
    ]
