# Generated by Django 3.2.3 on 2022-01-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220120_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
