# Generated by Django 3.2.3 on 2022-01-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notice_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
