# Generated by Django 3.2.3 on 2022-01-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notice_date_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
