# Generated by Django 3.2.3 on 2022-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220122_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('file', models.FileField(upload_to='docs/notices/%Y/%m/%d')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='news_file',
        ),
    ]
