# Generated by Django 3.2.3 on 2022-01-22 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
