# Generated by Django 3.2.3 on 2022-01-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_notice_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='notice_category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.noticecategory'),
            preserve_default=False,
        ),
    ]
