# Generated by Django 3.2.3 on 2021-11-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
