# Generated by Django 3.2.3 on 2021-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Bi', 'Bisexual'), ('Other', 'Other')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
