# Generated by Django 3.2.3 on 2021-10-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_subject_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='exambank',
            name='file',
            field=models.FileField(default=1, upload_to='files/exam_bank/%Y/%m/'),
            preserve_default=False,
        ),
    ]
