# Generated by Django 3.2.3 on 2021-10-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('admissions', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='in_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.studentclass'),
        ),
    ]
