# Generated by Django 3.2.3 on 2021-10-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_auto_20211013_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
