# Generated by Django 3.2.3 on 2021-12-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_journalist',
            field=models.BooleanField(default=False),
        ),
    ]
