# Generated by Django 3.2.3 on 2021-10-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscibers',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
