# Generated by Django 3.2.3 on 2021-10-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailsubscibers_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
