# Generated by Django 3.2.3 on 2021-11-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='images/utils/%Y/%m'),
        ),
    ]
