# Generated by Django 3.2.3 on 2021-10-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20211013_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='hod',
        ),
    ]
